In [1]:
from pyfmi.common.io import ResultDymolaBinary
import pandas as pd
import sys
import numpy as np
from  plotly.offline import plot
from plotly.graph_objs import *
      # get the data from the values dictionary
mat=ResultDymolaBinary('TestValues.mat')
mat_name=mat.name
mat_name

['Time',
 '_dummy',
 '_derdummy',
 'const.k',
 'const.y',
 'Coal',
 'const1.k',
 'const1.y',
 'Natural_Gas',
 'const2.k',
 'const2.y',
 'Petroleum',
 'const3.k',
 'const3.y',
 'Nuclear',
 'const4.k',
 'const4.y',
 'Renewable',
 'const5.k',
 'const5.y',
 'Conversion_Losse',
 'const6.k',
 'const6.y',
 'Residential',
 'const7.k',
 'const7.y',
 'Commercial',
 'const8.k',
 'const8.y',
 'Industrial',
 'const9.k',
 'const9.y',
 'Transportation']

In [2]:
Node=[mat_name]
for y in Node:
    data_1=[data for data in y if ".k" not in data]
    data_2=[data for data in data_1 if ".y" not in data]
    Data1=[data for data in data_2 if "_" not in data]
    Data=[data for data in Data1 if "Time" not in data]
Str=[ ]
for DATA in Data:
    Str.append(DATA)
len_data=len(Data)
for i in Data:
    time=mat.get_variable_data(i).t

Value=[]
for i in Data:
    value=mat.get_variable_data(i).x
    Value.append(value)
display(Data)
display(Value)


['Coal',
 'Petroleum',
 'Nuclear',
 'Renewable',
 'Residential',
 'Commercial',
 'Industrial',
 'Transportation']

[array([6157., 6157.], dtype=float32),
 array([387., 387.], dtype=float32),
 array([2383., 2383.], dtype=float32),
 array([1240., 1240.], dtype=float32),
 array([-1418., -1418.], dtype=float32),
 array([-1266., -1266.], dtype=float32),
 array([-1017., -1017.], dtype=float32),
 array([-541., -541.], dtype=float32)]

In [3]:
def is_negated(self, name):
        """
        Returns True if the given name corresponds to a negated result vector.
        
        Parameters::
        
            name -- 
                Name of the variable/parameter/constant.
                
        Returns::
        
            True if the result should be negated
        """
        varInd  = self.get_variable_index(name)
        dataInd = self.raw['dataInfo'][1][varInd]
        if dataInd<0:
            return True
        else:
            return False
for i in Data:
    value=mat.is_negated(i)
SourceSupply = []



for i in range(0, len_data):
    print("Enter the item for source supply")
    item = str(input())
    SourceSupply.append(item)
len_source=len(SourceSupply)
Link_color=['#262C46','#ff3344','#ffbbcc','#776647','#446677','#336677','#448899','#556677']
len_color=len(Link_color)
Supply=[]
Colors_1=[]
for i in  range(0,len_data):
    for j in range(0,len_source):
        if (SourceSupply[i]==Data[j]):
            Supply.append(j)
            Colors_1.append(Link_color[j])





Enter the item for source supply
Coal
Enter the item for source supply
Industrial
Enter the item for source supply
Renewable
Enter the item for source supply
Nuclear
Enter the item for source supply
Transporation
Enter the item for source supply
Petroleum
Enter the item for source supply
Residential
Enter the item for source supply
Commercial


In [4]:
Transformation = []

for i in range(0, len_data):
    
    print("Enter the item for Transformation supply")
    item = str(input())
    Transformation.append(item)
len_transformation=len(Transformation)
Trans=[]
Colors_2=[]
for i in  range(0,len_data):
    for j in range(0,len_transformation):
        if (Transformation[i]==Data[j]):
            Trans.append(j)
            Colors_2.append(Link_color[j])




Enter the item for Transformation supply
Nuclear
Enter the item for Transformation supply
Transportation
Enter the item for Transformation supply
Petroleum
Enter the item for Transformation supply
Residential
Enter the item for Transformation supply
Commercial
Enter the item for Transformation supply
Coal
Enter the item for Transformation supply
Industrial
Enter the item for Transformation supply
Coal


In [5]:
Consumption = []



for i in range(0,len_data):
    print("Enter the item for Consumption supply")
    item = str(input())
    Consumption.append(item)
len_consumption=len(Consumption)
consume=[]
Colors_3=[]
for i in  range(0,len_data):
    for j in range(0,len_consumption):
        if (Consumption[i]==Data[j]):
            consume.append(j)
            Colors_3.append(Link_color[j])
Source=np.concatenate((Supply,Trans))
Target=np.concatenate((Trans,consume))
Colors=np.concatenate((Colors_1,Colors_2,Colors_3))

Enter the item for Consumption supply
Residential
Enter the item for Consumption supply
Commercial
Enter the item for Consumption supply
Petroleum
Enter the item for Consumption supply
Coal
Enter the item for Consumption supply
Industrial
Enter the item for Consumption supply
Renewable
Enter the item for Consumption supply
Nuclear
Enter the item for Consumption supply
Industrial


In [6]:
from  plotly.offline import plot
from plotly.graph_objs import *


trace1 = {
  "link": {
    "color": Colors,
    "value": [6157,6157,387,387,2383,2383,1240,1240,1240,1240,-1418,345,4555,6455,4554,665,6545,657,543,656,7666,6563,3454], 
    "source": Source, 
    "target": Target
  }, 
  "node": {
    "pad": 10, 
    "line": {
      "color": "Black", 
      "width": 0.5
    }, 
    "color": ['#262C46','#ff3344','#ffbbcc','#776647','#446677','#336677','#448899','#556677'], 
    "label":Str,
    "thickness": 30
  }, 
  "type": "sankey", 
  "domain": {
    "x": [0, 1], 
    "y": [0, 1]
  }, 
  "orientation": "h", 
  "valueformat": ".0f"
}
data = Data([trace1])

fig = Figure(data=data)
plot(fig)





/home/raviy/anaconda3/lib/python3.8/site-packages/plotly/graph_objs/_deprecations.py:31: DeprecationWarning:

plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.




'temp-plot.html'